name: Build LaTeX Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Pour lancer manuellement

jobs:
  build:
    runs-on: windows-2022  # Runner Windows
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login latexregistry1750034388.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
    
    - name: Build Docker image
      run: |
        docker build -t latexregistry1750034388.azurecr.io/latex-windows:latest .
        docker build -t latexregistry1750034388.azurecr.io/latex-windows:${{ github.sha }} .
    
    - name: Push to ACR
      run: |
        docker push latexregistry1750034388.azurecr.io/latex-windows:latest
        docker push latexregistry1750034388.azurecr.io/latex-windows:${{ github.sha }}
    
    - name: Verify image
      run: docker images latexregistry1750034388.azurecr.io/latex-windows
